### ISSUE TITLE
Support Go modules

### ISSUE THREAD

**Issue by rumyantseva** [go-reform/reform#170] opened 2018-08-21 14:56 UTC
As [Go Modules](https://github.com/golang/go/wiki/Modules) are going to be presented as a part of Go 1.11, it might make sense to start supporting them.

**Comment by bikbah** [comment] 2018-08-22 09:38
duplicate of #161 ?

**Comment by AlekSi** [comment] 2018-08-22 09:55
Indeed! Thanks.

**Comment by dgellow** [comment] 2019-10-04 08:34
Any update on this issue? As far as I can tell @rumyantseva's PR solved the issue, but is now outdated.

**Comment by AlekSi** [comment] 2020-06-24 08:11
Done at #211.

**Closed by AlekSi** 2020-06-24 08:11 UTC
Labels: chore
