### ISSUE TITLE
hope to add cockroachdb support

### ISSUE THREAD

**Issue by goodforever** [go-reform/reform#234] opened 2020-08-02 12:06 UTC
hope to add cockroachdb support

**Comment by tooolbox** [comment] 2020-08-05 03:15
*Do or do not, there is no try.*

**Comment by AlekSi** [comment] 2020-08-05 05:20
Closing as duplicate of #112.

**Closed by AlekSi** 2020-08-05 05:20 UTC

**Comment by AlekSi** [comment] 2020-08-05 05:22
To clarify – it might actually _just work_ now: CockroachDB speaks PostgreSQL protocol, after all. It just wasn't tested.
