### ISSUE TITLE
Skip sqlite3 tables with incorrect table_info

### ISSUE THREAD

**Issue by eschizoid** [go-reform/reform#180] opened 2018-11-10 10:37 UTC
I have a third party database that I cannot change it. Is there a way to silently fail and still generate the _correct_ entities?

```
reform-db: 2018/11/10 04:33:51.656895 cmd_init_sqlite3.go:85: no such module: spellfix1
panic: no such module: spellfix1

goroutine 1 [running]:
gopkg.in/reform.v1/internal.(*Logger).Fatalf(0xc0000938f0, 0x45377d0, 0x2, 0xc000348a60, 0x1, 0x1)
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/internal/logger.go:51 +0x107
main.initModelsSQLite3(0xc00009c8a0, 0xc0000dbbd0, 0x400b9bd, 0x44dd240)
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/reform-db/cmd_init_sqlite3.go:85 +0x469
main.cmdInit(0xc00009c8a0, 0xc00001e004, 0x1f)
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/reform-db/cmd_init.go:184 +0xb2f
main.main()
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/reform-db/main.go:128 +0x3a4
```

Something like the following:

https://stackoverflow.com/questions/38425835/reflecting-sqlite-database-with-spellfix1-tables

Edit:
Even better, something like `--skip-tables` I think would be less invasive?

**Comment by eschizoid** [comment] 2018-11-10 10:38
```reform-db: 2018/11/10 04:33:51.656895 cmd_init_sqlite3.go:85: no such module: spellfix1
panic: no such module: spellfix1

goroutine 1 [running]:
gopkg.in/reform.v1/internal.(*Logger).Fatalf(0xc0000938f0, 0x45377d0, 0x2, 0xc000348a60, 0x1, 0x1)
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/internal/logger.go:51 +0x107
main.initModelsSQLite3(0xc00009c8a0, 0xc0000dbbd0, 0x400b9bd, 0x44dd240)
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/reform-db/cmd_init_sqlite3.go:85 +0x469
main.cmdInit(0xc00009c8a0, 0xc00001e004, 0x1f)
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/reform-db/cmd_init.go:184 +0xb2f
main.main()
	/Users/mgonzalez/go/src/gopkg.in/reform.v1/reform-db/main.go:128 +0x3a4```

**Comment by AlekSi** [comment] 2018-11-12 08:58
Is it the same as #174?

**Comment by eschizoid** [comment] 2018-11-12 15:39
@AlekSi Yes, you want me to close this one?

**Comment by AlekSi** [comment] 2018-11-12 15:49
Closing as duplicate of #174.

**Comment by AlekSi** [comment] 2018-11-12 16:18
Ok, that's a somewhat different issue. Reopening.
The proper fix is to log an error and continue to the next loop iteration [there](https://github.com/go-reform/reform/blob/91ede32b372b393da8b04541c5d02aba10eb378d/reform-db/cmd_init_sqlite3.go#L85). PRs are welcome.

**Comment by eschizoid** [comment] 2018-11-12 19:46
@AlekSi I feel that this behavior should be configurable. How you feel about adding an extra flag to `comand-db`. Either way, I can take the work :) (just checking what are your thoughts about it.)

**Comment by Fair2Dare** [comment] 2019-11-01 00:27
Is this flag still needed? I can give this a shot

**Closed** 2020-07-19 11:37 UTC
Labels: feature, help-wanted
