### ISSUE TITLE
Improved documentation & examples 

### ISSUE THREAD

**Issue by sebastianmacias** [go-reform/reform#105] opened 2017-02-05 18:29 UTC
It would help new comers to provide a more complete documentation like http://jinzhu.me/gorm/ with additional examples besides what is in the godoc.org and README pages.

**Comment by AlekSi** [comment] 2017-02-05 18:39
Absolutely. See #8.

Do you have some specific questions?

**Comment by AlekSi** [comment] 2017-02-10 09:36
Closing as a duplicate of #8.

Feel free to ask specific questions there or comment on #8.

**Closed by AlekSi** 2017-02-10 09:36 UTC
